pull_request_rules:
  - name: automatic merge
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
    conditions:
    - label!=work-in-progress
    - '#approved-reviews-by>=1'
    - status-success=continuous-integration/travis-ci/pr
